name: ⚙️ CI
on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: ⬇️ Checkout repository
      - uses: pnpm/action-setup@v4
        name: 🛠️ Setup pnpm
        with:
          version: 9.9.0
      - uses: actions/setup-node@v4
        name: 📦 Setup Node.js
        with:
          node-version: 20
          cache: pnpm
      - name: 🔍 Install dependencies
        run: pnpm install --frozen-lockfile
      - name: 🧹 Lint
        run: pnpm lint --filter=spreadorm
      - name: 🏗️ Build
        run: pnpm build --filter=spreadorm
      - name: 🧪 Test
        run: pnpm test
